import Image from "next/image";
import Head from "next/head";

export default function RootLayout({ children }) {
  return (
    <div className="flex justify-center align-center bg-body">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="stylesheet" href="https://use.typekit.net/gnc1lsn.css" /> */}
      </Head>
      <div className="w-2/4 mt-20 bg-white">
        <nav className="px-6 h-16 bg-darkBlue flex item-center">
          <div className="flex">
            <Image
              src="/spout-logo-dark.svg"
              alt="Spout Logo"
              width={80}
              height={80}
            />
          </div>
        </nav>
        <div className="flex flex-col md:flex-row h-max">
          {/* Sidebar */}
          <div className="w-full md:w-sidebar bg-white uppercase text-xs border-r-2 md:border-e-2 md:border-e-2 text-lightGray">
            <div className="flex flex-col">
              <h1 className="font-bold border-b-2 py-5 px-3 text-darkBlue">
                Select payment method
              </h1>
              <NavLink
                href="#"
                text="Card"
                icon="/card-menu-icon.svg"
                className="icon-dark group hover:text-white"
              />
              <NavLink
                href="#"
                text="Bank"
                icon="/bank-menu-icon.svg"
                className="group hover:text-white"
              />
              <NavLink
                href="#"
                text="Transfer"
                icon="/transfer-menu-icon.svg"
                className="group hover:text-white"
              />
              <NavLink
                href="#"
                text="USSD"
                icon="/ussd-menu-icon.svg"
                className="group hover:text-white"
              />
              <NavLink
                href="#"
                text="PayAttitude"
                icon="/payattitude-menu-icon.svg"
                className="group capitalize hover:text-white"
              />
              <NavLink
                href="#"
                text="Paycode"
                icon="/spoutpay-logo.svg"
                className="group hover:text-white"
              />
              <NavLink
                href="#"
                text="QR Code"
                icon="/qr-logo.svg"
                className="group hover:text-white"
              />
            </div>
          </div>
          {/* Main Content */}
          <div className="w-full md:w-full bg-white">
            <div className="border-b-2 py-4 px-3 flex justify-end">
              <div className="user-info">
                <p>email@gmail.com</p>
                <p>Balance</p>
              </div>
            </div>
            {children}
          </div>
        </div>
      </div>
    </div>
  );
}

// NavLink Component for internal navigation
function NavLink({ href, text, icon, className }) {
  return (
    <a
      href={href}
      className="flex border-b-2 border-slate-100 gap-2 px-2 py-4 text-dark hover:bg-gray-700 hover:border-b-0 hover:border-yellow-300 hover:border-e-8 hover:text-white block"
    >
      <div className={className}>
        <Image src={icon} width={20} height={20} alt={text} className="icon" />
      </div>
      {text}
    </a>
  );
}
