import Head from "./head";
import "./styles/globals.css";
import { Varela_Round } from "next/font/google";

const varela = Varela_Round({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head />
      <body className={varela.className}>{children}</body>
    </html>
  );
}
