import Head from "next/head";

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <title>Spoutpay</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex justify-center align-center bg-white">
        {children}
      </div>
    </>
  );
}
