import Head from "next/head";
import Image from "next/image";

export default function PaymentLayout({ children }) {
  return (
    <>
      <Head>
        <title>Spoutpay</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex justify-center align-center bg-white">
        <div className="w-2/4 mt-20 bg-white">
          <nav className="px-6 h-16 bg-dark-blue flex item-center">
            <div className="flex">
              <Image
                src="/spout-logo-dark.svg"
                alt="Spout"
                width="0"
                height="0"
                style={{ width: "60px", height: "60px" }}
                priority={true}
              />
            </div>
          </nav>
          {children}
        </div>
      </div>
    </>
  );
}
